version: 2

sources:
  - name: raw
    database: beaming-ring-485210-b4
    schema: gz_raw_data
    loader: bigquery
    description: "Raw data coming from BigQuery"

    tables:

      - name: sales
        identifier: raw_gz_sales
        description: "Sales data with one row per product per order"
        loaded_at_field: date_date

        tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - orders_id
              - pdt_id

        columns:
          - name: date_date
            description: "Date of the purchase"

          - name: orders_id
            description: "Unique identifier of the order"

          - name: pdt_id
            description: "Unique identifier of the product"

          - name: revenue
            description: "Revenue generated for the product"

          - name: quantity
            description: "Quantity sold"


      - name: product
        identifier: raw_gz_product
        description: "Product catalog with purchase prices"

        columns:
          - name: products_id
            description: "Unique product identifier"
            tests:
              - unique
              - not_null
              
          - name: purchse_price
            description: "Purchase price of the product"


      - name: ship
        identifier: raw_gz_ship
        description: "Shipping data for each order"

        columns:
          - name: orders_id
            description: "Unique identifier of the order"
            tests:
              - unique
              - not_null

          - name: shipping_fee
            description: "Shipping fee charged to the customer"

          - name: logcost
            description: "Logistic cost of the shipment"

          - name: ship_cost
            description: "Cost of shipping"


      - name: adwords
        identifier: raw_gz_adwords


      - name: bing
        identifier: raw_gz_bing


      - name: criteo
        identifier: raw_gz_criteo


      - name: facebook
        identifier: raw_gz_facebook



models:

#test int_campaigns

  - name: int_campaigns
    description: "Unified campaigns table (union all of adwords, bing, criteo, facebook staging models)"
    
    columns:
      # Primary key ( date + campaign_name + source)
      - name: date_date
        description: "Campaign date"
        tests: [not_null]
        
      - name: campaign_name
        description: "Campaign name"
        tests: [not_null]

      - name: paid_source
        description: "Marketing source (adwords/bing/criteo/facebook)"
        tests: [not_null]

      # Tests sur les métriques
      - name: ads_cost
        description: "Advertising cost"
        tests: [not_null]

      - name: impression
        description: "Number of impressions"
        tests: [not_null]

      - name: click
        description: "Number of clicks"
        tests: [not_null]
  
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date_date
            - campaign_name
            - paid_source

#test int_campaigns_days

  - name: int_campaigns_day
    description: "Daily aggregated marketing campaigns metrics (from int_campaigns)"

    columns:
      - name: date_date
        description: "Day"
        tests: [not_null]

      - name: paid_source
        description: "Marketing source"
        tests: [not_null]

      - name: ads_cost
        description: "Total daily ads cost"
        tests: [not_null]

      - name: impression
        description: "Total daily impressions"
        tests: [not_null]

      - name: click
        description: "Total daily clicks"
        tests: [not_null]

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date_date
            - paid_source

#test finance_campaigns_days

  - name: finance_campaigns_day
    description: "Daily finance KPIs joined with daily ads performance, including ads_margin"

    columns:
      - name: date
        tests: [not_null, unique]

      - name: ads_margin
        tests: [not_null]


